---
- name: Oracle database and GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  vars_files:
    - oracle_gp_vars.yml
  vars:
    extract_name: "ext_{{ inventory_hostname }}"
    replicat_name: "rep_{{ inventory_hostname }}"