---
- name: SnapMirror Break via ONTAP CLI (AAP)
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap
  vars:
    netapp_hostname: "{{ netapp_hostname }}"
    netapp_username: "{{ netapp_username }}"
    netapp_password: "{{ netapp_password }}"
  tasks:
    - name: Testing job Actual Job is commented as we are testing
      netapp.ontap.na_ontap_ssh_command:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        accept_unknown_host_keys: true
        command: >
          "{{ item }}"
          # snapmirror show
          # -destination-path {{ destination_svm }}:{{ destination_volume }}
        privilege: admin
      register: snapmirror_show
      failed_when: false
      loop: 
        - snapmirror show -destination-path Application_UAT:Mirror_ScriptTest_vol1 -fields state,status
        - snapmirror show -destination-path Application_UAT:Mirror_ScriptTest_vol1 -fields state,status
    
    # - name: Validate SnapMirror relationship exists
    #   netapp.ontap.na_ontap_ssh_command:
    #     hostname: "{{ netapp_hostname }}"
    #     username: "{{ netapp_username }}"
    #     password: "{{ netapp_password }}"
    #     accept_unknown_host_keys: true
    #     command: >
    #       "{{ item }}"
    #       # snapmirror show
    #       # -destination-path {{ destination_svm }}:{{ destination_volume }}
    #     privilege: admin
    #   register: snapmirror_show
    #   failed_when: false
    #   loop: 
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror update -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror quiesce -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror break -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
    #     - snapmirror update -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror quiesce -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
    #     - snapmirror break -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
