---
# - name: Installing netapps collection
#   hosts: localhost
#   connection: local
#   gather_facts: no
#   tasks:
#     # - name: Get Python dependencies
#     #   ansible.builtin.shell: pip3 list |grep para
      
#     # - name: Installing collection
#     #   ansible.builtin.shell: "ansible-galaxy collection install netapp-ontap-23.3.0.tar.gz -p /usr/share/ansible/collections/ansible_collections"
  
#     - name: adding to known hosts
#       ansible.builtin.shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

- name: SnapMirror Break via ONTAP CLI (AAP)
  hosts: localhost
  gather_facts: no

  collections:
    - netapp.ontap

  vars:
    netapp_hostname: "{{ netapp_hostname }}"
    netapp_username: "{{ netapp_username }}"
    netapp_password: "{{ netapp_password }}"

    destination_svm: "dest_svm"
    destination_volume: "dest_vol"

  tasks:
    - name: Testing job Actual Job is commented as we are testing
      netapp.ontap.na_ontap_ssh_command:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        accept_unknown_host_keys: true
        command: >
          "{{ item }}"
          # snapmirror show
          # -destination-path {{ destination_svm }}:{{ destination_volume }}
        privilege: admin
      register: snapmirror_show
      failed_when: false
      loop: 
        - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
        - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
    
    # - name: Validate SnapMirror relationship exists
    #   netapp.ontap.na_ontap_ssh_command:
    #     hostname: "{{ netapp_hostname }}"
    #     username: "{{ netapp_username }}"
    #     password: "{{ netapp_password }}"
    #     accept_unknown_host_keys: true
    #     command: >
    #       "{{ item }}"
    #       # snapmirror show
    #       # -destination-path {{ destination_svm }}:{{ destination_volume }}
    #     privilege: admin
    #   register: snapmirror_show
    #   failed_when: false
    #   loop: 
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror update -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror quiesce -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror break -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest  -source-path Application_UAT:Mirror_ScriptTest_vol1
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol1_dest -fields state,status
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
    #     - snapmirror update -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror quiesce -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status
    #     - snapmirror break -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest  -source-path Application_UAT:Mirror_ScriptTest_vol2
    #     - snapmirror show -destination-path DR_Training_Testing:Mirror_ScriptTest_vol2_dest -fields state,status



