---
- name: Installing netapps collection
  hosts: localhost
  connection: local
  tasks:
    - name: ls
      ansible.builtin.shell: ls -la
      
    - name: Installing collection
      ansible.builtin.shell: "ansible-galaxy collection install netapp.ontap-23.3.0.tar.gz"
  
    - name: verifing
      ansible.builtin.shell: "ansible-galaxy collection list"
