---
- name: Oracle GoldenGate Switchover on Solaris
  hosts: all
  become: yes
 # become_user: "{{ oracle_user }}"
  gather_facts: no
  vars_files:
    - oracle_gp_vars.yml  
  environment: "{{ ogg_env }}"
  tasks:
    - name: Testing the remote server environment
      ansible.builtin.shell: env
      register: environment_vars
      when: inventory_hostname == "test.server.local"


    - ansible.builtin.debug:
        msg: "{{ environment_vars }}"
      when: inventory_hostname == "test.server.local"


    - name: Open New primary in RW | Need to execute on ALL hosts in Standby
      ansible.builtin.shell: |
        ifconfig
        hostname
      when: "'dr_web' in group_names"
