---
- name: Oracle GoldenGate Switchover on Solaris
  hosts: all
  become: yes
 # become_user: "{{ oracle_user }}"
  gather_facts: no
  vars_file: oracle_gp_vars.yml
  environment: "{{ ogg_env }}"
  tasks:
    - name: Testing the remote server environment
      ansible.builtin.shell: env
      register: environment_vars
      when: inventory_hostname == "dc_db_1"


    - ansible.builtin.debug:
        msg: "{{ environment_vars }}"
      when: inventory_hostname == "dc_db_1"

