---
- name: Oracle database and GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  vars_files:
    - oracle_gp_vars.yml  
  tasks:
    - name: verify Ready for switchover on primary
      ansible.builtin.shell: |
        . ~/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE SWICHOVER TO RETUATDG Verify;
        EXIT;
        EOF
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      
    - name: Job Queue process to 0 | No more schedular jobs will RUN on DB
      ansible.builtin.shell: |
        . ~/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0 SID='*';
        EXIT;
        EOF
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      
    - name: Stop Extract on Source Database
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP EXTRACT {{ extract_name }}
        INFO EXTRACT {{ extract_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"  
      when: inventory_hostname == "dc_db_1"
      register: stop_extract
      
      
    - name: Wait for Replicat to catch up on Target
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        LAG REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"        
      when: inventory_hostname == "dc_db_1"
      register: replicat_lag
      retries: 3
      delay: 5
      until: "'00:00:00' in replicat_lag.stdout"

    - name: Stop Replicat on Target
      shell: |
        . ~/.bash_profile      
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP REPLICAT {{ replicat_name }}
        INFO REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"        
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      register: stop_replicat
      
    - name: Stop manager on Source Database
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP mgr!
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"  
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      register: stop_mgr
      
    - name: Perform switchover on primary
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE SWICHOVER TO RETUATDG;
        EXIT;
        EOF
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
     
    - name: Open New primary in RW | Need to execute on ALL hosts in Standby
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE OPEN;
        EXIT;
        EOF
      when: "'dr_db' in group_names"
#  SELECT NAME,Instance_Name,DATABASE_ROLE,OPEN_MODE FROM v$Database,GV$Instance;
     
     ### primary and openmode read write
    - name: Verify Openmode and database_role #
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        SELECT NAME,Instance_Name,DATABASE_ROLE,OPEN_MODE FROM v$Database,V$Instance;
        EXIT;
        EOF
      register: Verify_Openmode  
      when: 
        -  inventory_hostname == "dr_db_1" or inventory_hostname == "dr_db_2"
        -  "'READ WRITE' in Verify_Openmode.stdout" 
        -  "'PRIMARY' in Verify_Openmode.stdout"
       
    - name: Open New Standby In Readonly Mode 
      ansible.builtin.shell: |
        . ~/.bash_profile &&
        srvctl start database -d RETUAT -o 'read only'
      # when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      
    - name:  Start MRP 
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
        EXIT;
        EOF
      #      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"