---
- name: Oracle GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  vars_files:
    - oracle_gp_vars.yml  
  tasks:
    - name: verify Ready for switchover on primary
      ansible.builtin.shell: |
        . ~/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE SWICHOVER TO RETUATDG Verify;
        EXIT;
        EOF
      when: "'dc_db_1' in group_names"
      	
    - name: Stop Extract on Source Database
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP EXTRACT {{ extract_name }}
        INFO EXTRACT {{ extract_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"  
      when: "'dc_db_1' in group_names"    
      register: stop_extract
      
      
    - name: Wait for Replicat to catch up on Target
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        LAG REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"        
      when: "'dc_db_1' in group_names"
      register: replicat_lag
      retries: 10
      delay: 5
      until: "'00:00:00' in replicat_lag.stdout"

    - name: Stop Replicat on Target
      shell: |
        . ~/.bash_profile      
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP REPLICAT {{ replicat_name }}
        INFO REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"        
      when: "'dc_db_1' in group_names"
      register: stop_replicat
      
    - name: Stop manager on Source Database
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP mgr!
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"  
      when: "'dc_db_1' in group_names"
      register: stop_mgr
      
    - name: Perform switchover on primary
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE SWICHOVER TO RETUATDG;
        EXIT;
        EOF
      when: "'dc_db_1' in group_names"

    - name: Open New primary in RW | Need to execute on ALL hosts in Standby
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE OPEN;
        EXIT;
        EOF
      when: "'dr_db' in group_names"
      
     ### primary and openmode read write
    - name: Verify Openmode and database_role #
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        SELECT NAME,Instance_Name,DATABASE_ROLE,OPEN_MODE FROM v$Database,GV$Instance;
        EXIT;
        EOF
      when: "'dr_db_1' in group_names"    
      
    - name: Open New Standby In Readonly Mode 
      ansible.builtin.shell: |
        . ~/.bash_profile &&
        srvctl start database -d RETUAT -o 'read only'
      when: "'dr_db_1' in group_names"
      
    - name:  Start MRP 
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
        EXIT;
        EOF
      when: "'dc_db_1' in group_names"    


      
    # - name: Start Extract on Target (New Primary)
    #   shell: |
    #     cd {{ ogg_home }}
    #     ./ggsci <<EOF
    #     START EXTRACT {{ extract_name }}
    #     INFO EXTRACT {{ extract_name }}
    #     EXIT
    #     EOF
    #   args:
    #     chdir: "{{ ogg_home }}"        
    #   when: "'dr_db' in group_names"
    #   register: start_extract_target

    # - name: Start Replicat on Source (Reverse Replication)
    #   shell: |
    #     cd {{ ogg_home }}
    #     ./ggsci <<EOF
    #     START REPLICAT {{ replicat_name }}
    #     INFO REPLICAT {{ replicat_name }}
    #     EXIT
    #     EOF
    #   args:
    #     chdir: "{{ ogg_home }}"        
    #   when: "'dc_db' in group_names"
    #   register: start_replicat_source
