---
- name: Oracle GoldenGate Switchover on Solaris
  hosts: all
  become: yes
 # become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  tasks:
    - name: Testing the remote server environment
      ansible.builtin.shell: env
      register: environment_vars

    - ansible.builtin.debug:
        msg: "{{ environment_vars }}"
