
---
- name: Oracle GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  
  tasks:
    - name: Verify Openmode and database_role #
      ansible.builtin.shell: |
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        SELECT NAME,Instance_Name,DATABASE_ROLE,OPEN_MODE FROM v$Database,GV$Instance;
        EXIT;
        EOF
      when: "'dc_db' in group_names"
      
    - name: Stop Extract on Source Database
      shell: |
        cd {{ ogg_home }}
        ./ggsci <<EOF
        INFO EXTRACT {{ extract_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"  
      when: "'dc_db' in group_names"      
      register: stop_extract    
  

