---
- name: Oracle database and GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  vars_files:
    - oracle_gp_vars.yml
  vars:
    extract_name: "ext_{{ inventory_hostname }}"
    replicat_name: "rep_{{ inventory_hostname }}"
  tasks:
## Can not execute it as GG is not configured in the DR yet. Will execute it manually after switchover is done and DR is primary  
#     - name: sw3 |Stop manager on Source Database
#       shell: |
#         . ~/.bash_profile
#         cd {{ ogg_home }}
#         ./ggsci <<EOF
#         STOP mgr!
#         EXIT
#         EOF
#       args:
#         chdir: "{{ ogg_home }}"  
# #      when: "'dc_db_1' in group_names"
#       when: inventory_hostname == "dc_db_1"
#       register: stop_mgr
      
    - name: sw3 |Perform switchover on primary
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
        ALTER DATABASE SWICHOVER TO RETUATDG;
        EXIT;
        EOF
      args:  
          executable: /bin/bash  
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dr_db_1"  