---
- name: Oracle database and GoldenGate Switchover on Solaris
  hosts: dr_web:dc_web
  become: yes
  become_user: "{{ oracle_user }}"
  gather_facts: no
  environment: "{{ ogg_env }}"
  vars_files:
    - oracle_gp_vars.yml
  vars:
    extract_name: "ext_{{ inventory_hostname }}"
    replicat_name: "rep_{{ inventory_hostname }}"
  tasks:      
    - name: sw2 |Stop Extract on Source Database
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP EXTRACT {{ extract_name }}
        INFO EXTRACT {{ extract_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"
        executable: /bin/bash  
      when: inventory_hostname == "dc_db_1"
      register: stop_extract
      
      
    - name: sw2 |Wait for Replicat to catch up on Target
      shell: |
        . ~/.bash_profile
        cd {{ ogg_home }}
        ./ggsci <<EOF
        LAG REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"
        executable: /bin/bash        
      when: inventory_hostname == "dc_db_1"
      register: replicat_lag
      retries: 3
      delay: 5
      until: "'00:00:00' in replicat_lag.stdout"

    - name: sw2 |Stop Replicat on Target
      shell: |
        . ~/.bash_profile      
        cd {{ ogg_home }}
        ./ggsci <<EOF
        STOP REPLICAT {{ replicat_name }}
        INFO REPLICAT {{ replicat_name }}
        EXIT
        EOF
      args:
        chdir: "{{ ogg_home }}"
        executable: /bin/bash        
#      when: "'dc_db_1' in group_names"
      when: inventory_hostname == "dc_db_1"
      register: stop_replicat
# Moved them to stage 3 for better control      
#     - name: sw2 |Stop manager on Source Database
#       shell: |
#         . ~/.bash_profile
#         cd {{ ogg_home }}
#         ./ggsci <<EOF
#         STOP mgr!
#         EXIT
#         EOF
#       args:
#         chdir: "{{ ogg_home }}"  
# #      when: "'dc_db_1' in group_names"
#       when: inventory_hostname == "dc_db_1"
#       register: stop_mgr
      
#     - name: sw2 |Perform switchover on primary
#       ansible.builtin.shell: |
#         . ~/.bash_profile
#         cd {{ oracle_home }}/.bash_profile && sqlplus -S / as sysdba <<EOF
#         ALTER DATABASE SWICHOVER TO RETUATDG;
#         EXIT;
#         EOF
# #      when: "'dc_db_1' in group_names"
#       when: inventory_hostname == "dc_db_1"
          